### ISSUE TITLE
Mobile response

### ISSUE THREAD

**Issue by rabichawila** [tailable/pagination#4]
Thanks for the package.
But is there anyway of getting a mobile responsive buttons.

Like wrapping them when the device is small and putting them in a row when there is enough space.

![image](https://user-images.githubusercontent.com/37574136/107159340-041eb980-6998-11eb-9bd0-06be96857c16.png)

**Comment by jamesdordoy** [comment]
Hey @rabichawila 

You can slot the whole html and use anything you want so you can write your own responsive design.

Apologies but i dont have time to provide an example. At some point ill write some docs for this package
