### ISSUE TITLE
Invalid prop: type check failed for prop "data". Expected Object, got Array

### ISSUE THREAD

**Issue by sukhrobnurali** [tailable/pagination#7]
Giving error even if i do
        axios.get("http://laravel.test/api/users")
        .then(response => {
            this.users = response.data;
        })

: Invalid prop: type check failed for prop "data". Expected Object, got Array

**Comment by jamesdordoy** [comment]
Look at the Laravel docs: [https://laravel.com/docs/8.x/pagination#basic-usage](https://laravel.com/docs/8.x/pagination#basic-usage)
